# Generated by Django 4.1.5 on 2023-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.AddField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[("all", "18 AND ABOVE"), ("child", "17 AND BELOW")],
                max_length=20,
                null=True,
            ),
        ),
    ]
