# Generated by Django 4.1.5 on 2023-01-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0017_movie_date_aired_movie_type"),
        ("users", "0003_remove_user_age_user_age_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                related_name="user_watchlist", to="movies.movie"
            ),
        ),
    ]
