# Generated by Django 4.1.5 on 2023-01-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_image_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
    ]
