# Generated by Django 4.1.5 on 2023-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options_alter_category_slug"),
        ("movies", "0008_remove_movie_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="categories.category",
            ),
        ),
    ]
