# Generated by Django 4.1.5 on 2023-01-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_age_user_age_group"),
        ("categories", "0002_alter_category_options_alter_category_slug"),
        ("movies", "0010_alter_movie_category_alter_movie_trailer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="movies",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movies.trailer",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movies",
                to="users.admin",
            ),
        ),
    ]
