# Generated by Django 4.1.5 on 2023-01-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_movie_category_alter_movie_trailer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="movies.movie",
            ),
        ),
    ]
