# Generated by Django 4.1.5 on 2023-01-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_image_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
