# Generated by Django 4.1.5 on 2023-01-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_movie_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="trailer",
        ),
        migrations.AddField(
            model_name="trailer",
            name="movie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trailer",
                to="movies.movie",
            ),
        ),
    ]
