# Generated by Django 4.1.5 on 2023-01-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options_alter_category_slug"),
        ("movies", "0015_remove_movie_trailer_trailer_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ManyToManyField(
                related_name="movies", to="categories.category"
            ),
        ),
    ]
