# Generated by Django 4.1.5 on 2023-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0016_remove_movie_category_movie_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_aired",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("MOVIE", "movie"), ("SERIES", "series")],
                max_length=10,
                null=True,
            ),
        ),
    ]
