# Generated by Django 4.1.5 on 2023-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0017_movie_date_aired_movie_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("movie", "Movie"), ("series", "Series")],
                max_length=10,
                null=True,
            ),
        ),
    ]
